name: Android CI

on:
  push:
    branches:
      - android-ci
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: /opt/android-sdk
      ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17.0.1
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17.0.1'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: 30.0.3

      - name: Decrypt and setup Keystore
        run: |
          echo "${ANDROID_KEYSTORE}" | base64 --decode > debug.keystore
          mkdir -p ~/.android/
          touch ~/.android/repositories.cfg

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        run: firebase login --no-interactive --token $(cat app/google-services.json)

      - name: Distribute APK
        run: firebase appdistribution:distribute --app android:1:473619344732:android:598642f8174aac09efa599 --apk app/build/outputs/apk/debug/app-debug.apk --group-name="testers"