name: Android CI

# Allow the workflow to be triggered manually with inputs
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to build the APK from'
        required: true
        default: 'main'  # Default to the main branch if no input is provided

  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: /opt/android-sdk
      ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}

    steps:
      # Step 1: Checkout the branch provided as input
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}  # Use the branch provided by the user

      # Step 2: Set up JDK 17.0.1
      - name: Set up JDK 17.0.1
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17.0.1'

      # Step 3: Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: 30.0.3

      # Step 4: Decrypt and setup Keystore
      - name: Decrypt and setup Keystore
        run: |
          echo "${ANDROID_KEYSTORE}" | base64 --decode > release-keystore.jks
          mkdir -p ~/.android/
          touch ~/.android/repositories.cfg

      # Step 5: Build APK
      - name: Build APK
        run: ./gradlew assembleDebug

      # Step 6: Upload APK to Firebase App Distribution
      - name: Upload APK to Firebase App Distribution
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: |
          curl -sL https://firebase.tools | bash
          firebase appdistribution:distribute app/build/outputs/apk/debug/app-debug.apk \
            --app $FIREBASE_APP_ID \
            --groups "testers"