name: Android CI/CD

on:
  push:
    branches: [ main ] # Or your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v4
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers # Replace with your tester group name
          file: app/build/outputs/apk/debug/app-debug.apk # Adjust path if needed

      # Optional: Add steps for running tests, building release APK, etc.