name: Firebase App Distribution

on:
  push:
    branches: [main]

jobs:
  build_and_distribute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17.0.1
        uses: actions/setup-java@v3
        with:
          java-version: 17.0.1

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        run: firebase login --no-interactive --token $(cat app/google-services.json)

      - name: Distribute APK
        run: firebase appdistribution:distribute --app android:1:473619344732:android:598642f8174aac09efa599 --apk app/build/outputs/apk/debug/app-debug.apk